[project]
name = "nanotitan"
description = "A lightweight PyTorch framework for training generative AI models. Derived from TorchTitan."
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "sky", email = "ski.akashh@gmail.com" }]
keywords = ["pytorch", "training", "llm"]
dependencies = [
    "torchdata>=0.8.0",
    "datasets>=2.21.0",
    "tokenizers>=0.22.1",
    "loguru>=0.7.3",
    "wandb>=0.23.1",
    "torch>=2.11.0,<2.12.0",
]
version = "0.1.0"

[project.urls]
GitHub = "https://github.com/ski-akash/nanotitan"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "ruff>=0.14.10",
    "ty>=0.0.31",
    "vulture>=2.14",
]
benchmarks = [
    "matplotlib>=3.9.0",
]

[tool.setuptools.packages.find]
where = [""]
include = ["nanotitan*"]

[tool.pytest.ini_options]
addopts = ["--showlocals"]
